version: '2.1'

volumes:
  jenkins-home:


services:
  jenkins:
    image: jenkins-rpi:20181028
    container_name: jenkins-rpi
    privileged: true
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
    - "50000:50000"
    - "10080:8080"
    volumes:
    - jenkins-home:/var/jenkins_home
    networks:
      jenkins-network:
          ipv4_address: 192.168.10.2

networks:
  jenkins-network:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
